spring:
  application:
    name: JobForge

  datasource:
    url: jdbc:postgresql://localhost:5432/jobboard
    username: jobforge_user
    password: Jobforge123!

  jpa:
    hibernate:
      ddl-auto: create-drop # automatically creates tables from JPA and the @Entity classes representing my tables
    show-sql: true
    properties:
      hibernate:
        format_sql: true

job:
  repost:
    cooldown-days: 7

security:
  jwt:
    secret: ${JWT_SECRET:QfT+pB+bT29qjRj0I6sF+vXw7L/sE4c2z1R8t1g5i7k=}
    access-expiration-ms: 900000   # 15m (JWT token lifespan)
    refresh-expiration-ms: 604800000 # 7d (refresh token lifespan)

  public-paths:
    - /api/users/signup
    - /api/users/login
    - /api/users/recover/**
    - /api/auth/renewAccessToken