spring:
  application:
    name: JobForge

  datasource:
    url: jdbc:postgresql://localhost:5432/jobboard
    username: jobforge_user
    password: Jobforge123!
  jpa:
    hibernate:
      ddl-auto: create # automatically creates tables from JPA and the @Entity classes representing my tables
    show-sql: true
    properties:
      hibernate:
        format_sql: true

job:
  repost:
    cooldown-days: 7

security:
  jwt:
    secret: ${JWT_SECRET:jobForge123!}
    access-expiration-ms: 900000   # 15m (JWT token lifespan)
    refresh-expiration-ms: 604800000 # 7d (refresh token lifespan)